# Run docker-compose build
# Run docker-compose up
# Live long and prosper

version: '3.7'

services:
  nginx:
    container_name: nginx
    restart: always
    image: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
     - ./client/dist:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask

  flask:
    container_name: flask
    restart: always
    image: flask
    build: ./server
    volumes:
    - ./server:/usr/src/app/server
    env_file:
     - .env

  data:
   container_name: app_data
   image: postgres:latest
   volumes:
     - /var/lib/postgresql
   command: "true"

  postgres:
   container_name: postgresql
   restart: always
   build: ./postgresql
   volumes:
     - data
   ports:
     - "6432:6432"
   env_file:
     - .env
